### ISSUE TITLE
API doesn't return multiple answers

### ISSUE THREAD

**Issue by bbkane** [ninoseki/digging#14]
Hello,

This API doesn't return multiple answers. Please see the following:

```
$ dig +short +noshort @8.8.8.8 linkedin.com TXT
linkedin.com.		3363	IN	TXT	"448e0dc03e935ecf66d81f1ce3c26b2f2fea13756c031ffc4be91749107f3a79"
linkedin.com.		3363	IN	TXT	"google-site-verification=8LaIeBMwr6K8qWeaGa4CEmfPKiZDwaT38t5mIrtaroI"
linkedin.com.		3363	IN	TXT	"v=spf1 ip4:199.101.162.0/25 ip4:108.174.3.0/24 ip4:108.174.6.0/24 ip4:108.174.0.0/24 ip6:2620:109:c00d:104::/64 ip6:2620:109:c006:104::/64 ip6:2620:109:c003:104::/64 ip6:2620:119:50c0:207::/64 ip4:199.101.161.130 mx mx:docusign.net ~all"
linkedin.com.		3363	IN	TXT	"google-site-verification=xAGz495k8RbGclhamQx1TkZSHDxOaEd95fOjc8xpbTA"
linkedin.com.		3363	IN	TXT	"google-site-verification=VE9BWhjbPPNmbr3ZJcwn5hLTsz7c5KPt3zXdYyaSnSQ"
linkedin.com.		3363	IN	TXT	"docusign=11f01284-dffc-40f9-8d56-57e5261ede3f"
linkedin.com.		3363	IN	TXT	"google-site-verification=anx3jpa6VKkTWRJKnglUIzm7UEn-ZCT2WqAfG7h-xOg"
linkedin.com.		3363	IN	TXT	"bf5fl8sny79w4c70jxp6cp3crkqtr7qk"
```

and

```
$ curl -X POST dns-digging.herokuapp.com -d "type=TXT&&name=linkedin.com&&server=8.8.8.8"
{"strings":"[\"bf5fl8sny79w4c70jxp6cp3crkqtr7qk\"]","ttl":"3273"}
```

**Comment by Grundel1979** [comment]
Adding to this: 
C:\Users\pterekho>dig a cameoproject.net.

; <<>> DiG 9.16.3 <<>> a cameoproject.net.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34726
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;cameoproject.net.              IN      A

;; ANSWER SECTION:
cameoproject.net.       14389   IN      A       165.160.13.20
cameoproject.net.       14389   IN      A       165.160.15.20

curl.exe -X POST dns-digging.herokuapp.com -d "type=A&&name=cameoproject.net"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    70  100    41  100    29     41     29  0:00:01 --:--:--  0:00:01   179
{"address":"165.160.13.20","ttl":"14021"}

**Comment by ninoseki** [comment]
Excuse my laziness.
I changed to return a list of resources in the API.

**Comment by Grundel1979** [comment]
> Excuse my laziness.
> I changed to return a list of resources in the API.

Thank you!
